# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            Wierzba
tagline:          'blog o programowaniu'
description:      'Luźny blog o programowaniu i rzeczach z nim związanych :D'
url:              https://wierzba13.github.io/
baseurl:          '/wierzba'
                  # the optional subpath of your site, e.g. "/blog"
                  # NB: This applies to all pages in your Jekyll site.
                  # If you want to move just the blog index pages but keep
                  # other pages at root, see the paginate_path and
                  # sidebar_blog_link below.

plugins:
  - jekyll-feed
  - jekyll-gist

# Sidebar link settings
sidebar_home_link:  true
# sidebar_blog_link:  '/blog'   # By default, your home page is your blog
                                # page. If you change your paginate_path,
                                # set this to the root of the paginate_path
                                # to enable a separate blog link.

remote_theme: fongandrew/hydeout
disqus:  shortname: wierzba